import os
from dotenv import load_dotenv
load_dotenv()

OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY")

SEARCH_ENDPOINT = os.getenv("AZURE_SEARCH_ENDPOINT")
SEARCH_KEY = os.getenv("AZURE_SEARCH_KEY")
INDEX_NAME = "kb-index"

SERVICENOW_INSTANCE = os.getenv("SERVICENOW_INSTANCE")
SERVICENOW_USER = os.getenv("SERVICENOW_USER")
SERVICENOW_PASSWORD = os.getenv("SERVICENOW_PASSWORD")

CONFLUENCE_BASE_URL=os.getenv("CONFLUENCE_BASE_URL")
CONFLUENCE_API_TOKEN=os.getenv("CONFLUENCE_API_TOKEN")
CONFLUENCE_EMAIL=os.getenv("CONFLUENCE_EMAIL")
CONFLUENCE_SPACE_KEY = "KB"

EMAIL_USER=os.getenv("EMAIL_USER")
EMAIL_PASSWORD=os.getenv("EMAIL_PASSWORD")

EMAIL_SMTP_SERVER="smtp.gmail.com"
EMAIL_SMTP_PORT=587